Added oracle to the search_path for Orafce
yugabyte/yb-voyager pull request #1240
Opened 2023-12-07 08:18 UTC by shubham-yb

Added the fix for https://yugabyte.atlassian.net/browse/DB-6838 and a test case

2023-12-08 04:50 UTC, shubham-yb commented
Test runs: https://jenkins.dev.yugabyte.com/job/users/job/yb-voyager-testing/job/yb-voyager-testing-pipeline/1511/

2023-12-12 12:20 UTC, sanyamsinghal requested changes

2023-12-12 13:30 UTC, shubham-yb commented on migtests/tests/oracle/misc-tests/misc_tests_schema_data.sql
> +CREATE VIEW employee_yos (employee_id, full_name, yos) AS
Don't think other functions are required as of now. Adding a TODO for later.

2023-12-13 07:00 UTC, sanyamsinghal approved these changes
LGTM.
Make sure to verify the changes once again after those refactoring comments.
Also, verify all the automation tests for Oracle in Jenkins Pipelines.

2023-12-13 12:56 UTC, merged